# Generated by Django 3.2.1 on 2021-05-22 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=600)),
                ('publish_status', models.CharField(choices=[('published', 'published'), ('fail', 'fail')], max_length=20)),
                ('solve_status', models.CharField(choices=[('solved', 'solved'), ('not solved', 'not solved'), ('solving', 'solving')], max_length=20)),
                ('offer_price', models.CharField(max_length=16)),
                ('senders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
