# Generated by Django 3.2.1 on 2021-05-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLevelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TagLevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_level_two', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TegLevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_level_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.taglevelone')),
            ],
        ),
        migrations.DeleteModel(
            name='FactoryProblemModel',
        ),
    ]
