# Generated by Django 3.2.1 on 2021-05-23 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_auto_20210523_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=600)),
                ('publish_status', models.CharField(choices=[('published', 'published'), ('fail', 'fail')], default='published', max_length=20)),
                ('solve_status', models.CharField(choices=[('solved', 'solved'), ('not solved', 'not solved'), ('solving', 'solving')], default='not solved', max_length=20)),
                ('offer_price', models.CharField(max_length=16)),
                ('senders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tag_level_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.taglevelone')),
                ('tag_level_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.taglevelthree')),
                ('tag_level_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.tegleveltwo')),
            ],
        ),
    ]
