# Generated by Django 3.2.1 on 2021-05-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_factoryproblemmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagLevelOne',
            new_name='TagLevelOneModeModel',
        ),
        migrations.RenameModel(
            old_name='TagLevelThree',
            new_name='TagLevelThreeModel',
        ),
        migrations.RenameModel(
            old_name='TegLevelTwo',
            new_name='TegLevelTwoModel',
        ),
    ]
